//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo
    {
        public Combo()
        {
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public string C_Combo { get; set; }
        public string N_Combo { get; set; }
        public string Descrip_Combo { get; set; }
        public int Q_Stock { get; set; }
    
        public virtual Producto_Combo Producto_Combo { get; set; }
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
