//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Producto_Combo = new HashSet<Producto_Combo>();
        }
    
        public string C_Producto { get; set; }
        public string N_Producto { get; set; }
        public string Descrip_Producto { get; set; }
        public int Q_Stock { get; set; }
    
        public virtual ICollection<Producto_Combo> Producto_Combo { get; set; }
    }
}
