//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public string C_Usuario { get; set; }
        public string UserName { get; set; }
        public string Password_Usuario { get; set; }
        public string N_Usuario { get; set; }
        public string T_DireccionUsuario { get; set; }
        public string Telef_Cliente { get; set; }
    
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
