//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public string C_Venta { get; set; }
        public string C_Usuario { get; set; }
        public string D_FechVenta { get; set; }
        public double Q_Monto { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual VentaDetalle VentaDetalle { get; set; }
    }
}
